"""Add extended profile fields

Revision ID: b2f8d3e29050
Revises: 8e881f34c5ec
Create Date: 2026-06-19 16:58:57.592590+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2f8d3e29050"
down_revision: Union[str, Sequence[str], None] = "8e881f34c5ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_habit_definitions_habit_type"), table_name="habit_definitions"
    )
    op.create_index(
        op.f("ix_habit_definitions_habit_type"),
        "habit_definitions",
        ["habit_type"],
        unique=True,
    )
    op.add_column("users", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("gender", sa.String(length=20), nullable=True))
    op.add_column(
        "users", sa.Column("state_province", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "state_province")
    op.drop_column("users", "gender")
    op.drop_column("users", "age")
    op.drop_index(
        op.f("ix_habit_definitions_habit_type"), table_name="habit_definitions"
    )
    op.create_index(
        op.f("ix_habit_definitions_habit_type"),
        "habit_definitions",
        ["habit_type"],
        unique=False,
    )
    # ### end Alembic commands ###
