"""Add extended assessment fields

Revision ID: 174322890653
Revises: b2f8d3e29050
Create Date: 2026-06-19 18:45:01.194441+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "174322890653"
down_revision: Union[str, Sequence[str], None] = "b2f8d3e29050"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "carbon_assessments", sa.Column("housing_emission", sa.Float(), nullable=True)
    )
    op.add_column(
        "carbon_assessments", sa.Column("water_emission", sa.Float(), nullable=True)
    )
    op.add_column(
        "carbon_assessments", sa.Column("digital_emission", sa.Float(), nullable=True)
    )
    op.add_column(
        "carbon_assessments", sa.Column("shopping_emission", sa.Float(), nullable=True)
    )
    op.add_column(
        "carbon_assessments", sa.Column("offsets_total", sa.Float(), nullable=True)
    )
    op.add_column(
        "emission_inputs",
        sa.Column("vehicle_type", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs", sa.Column("fuel_type", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "emission_inputs", sa.Column("trips_per_week", sa.Integer(), nullable=True)
    )
    op.add_column(
        "emission_inputs",
        sa.Column("public_transport_usage", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("carpooling_frequency", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("air_travel_frequency", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("train_travel_frequency", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs", sa.Column("walking_cycling_hours", sa.Float(), nullable=True)
    )
    op.add_column(
        "emission_inputs",
        sa.Column("energy_efficiency_rating", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("heating_type", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("local_food_frequency", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs", sa.Column("food_waste_percentage", sa.Float(), nullable=True)
    )
    op.add_column(
        "emission_inputs",
        sa.Column("composting_frequency", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("ewaste_disposal_method", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs", sa.Column("daily_water_liters", sa.Float(), nullable=True)
    )
    op.add_column(
        "emission_inputs",
        sa.Column("shower_duration_minutes", sa.Float(), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("water_heating_type", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs", sa.Column("house_size_sqm", sa.Float(), nullable=True)
    )
    op.add_column(
        "emission_inputs",
        sa.Column("home_insulation_level", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs", sa.Column("screen_time_hours", sa.Float(), nullable=True)
    )
    op.add_column(
        "emission_inputs", sa.Column("streaming_hours", sa.Float(), nullable=True)
    )
    op.add_column(
        "emission_inputs", sa.Column("gaming_hours", sa.Float(), nullable=True)
    )
    op.add_column(
        "emission_inputs", sa.Column("new_clothes_monthly", sa.Integer(), nullable=True)
    )
    op.add_column(
        "emission_inputs",
        sa.Column("second_hand_purchases", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("electronics_purchases_yearly", sa.Integer(), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("commute_days_per_week", sa.Integer(), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("remote_work_percentage", sa.Float(), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("assessment_country", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("assessment_state", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("assessment_city", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "emission_inputs", sa.Column("composting_active", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "emission_inputs", sa.Column("tree_planting_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "emission_inputs",
        sa.Column("reusable_products_usage", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "emission_inputs",
        sa.Column("green_transport_choices", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("emission_inputs", "green_transport_choices")
    op.drop_column("emission_inputs", "reusable_products_usage")
    op.drop_column("emission_inputs", "tree_planting_count")
    op.drop_column("emission_inputs", "composting_active")
    op.drop_column("emission_inputs", "assessment_city")
    op.drop_column("emission_inputs", "assessment_state")
    op.drop_column("emission_inputs", "assessment_country")
    op.drop_column("emission_inputs", "remote_work_percentage")
    op.drop_column("emission_inputs", "commute_days_per_week")
    op.drop_column("emission_inputs", "electronics_purchases_yearly")
    op.drop_column("emission_inputs", "second_hand_purchases")
    op.drop_column("emission_inputs", "new_clothes_monthly")
    op.drop_column("emission_inputs", "gaming_hours")
    op.drop_column("emission_inputs", "streaming_hours")
    op.drop_column("emission_inputs", "screen_time_hours")
    op.drop_column("emission_inputs", "home_insulation_level")
    op.drop_column("emission_inputs", "house_size_sqm")
    op.drop_column("emission_inputs", "water_heating_type")
    op.drop_column("emission_inputs", "shower_duration_minutes")
    op.drop_column("emission_inputs", "daily_water_liters")
    op.drop_column("emission_inputs", "ewaste_disposal_method")
    op.drop_column("emission_inputs", "composting_frequency")
    op.drop_column("emission_inputs", "food_waste_percentage")
    op.drop_column("emission_inputs", "local_food_frequency")
    op.drop_column("emission_inputs", "heating_type")
    op.drop_column("emission_inputs", "energy_efficiency_rating")
    op.drop_column("emission_inputs", "walking_cycling_hours")
    op.drop_column("emission_inputs", "train_travel_frequency")
    op.drop_column("emission_inputs", "air_travel_frequency")
    op.drop_column("emission_inputs", "carpooling_frequency")
    op.drop_column("emission_inputs", "public_transport_usage")
    op.drop_column("emission_inputs", "trips_per_week")
    op.drop_column("emission_inputs", "fuel_type")
    op.drop_column("emission_inputs", "vehicle_type")
    op.drop_column("carbon_assessments", "offsets_total")
    op.drop_column("carbon_assessments", "shopping_emission")
    op.drop_column("carbon_assessments", "digital_emission")
    op.drop_column("carbon_assessments", "water_emission")
    op.drop_column("carbon_assessments", "housing_emission")
    # ### end Alembic commands ###
